#!/bin/bash

set -e

case "$1" in
    compile)
        cc $2
        ;;
    
    run)
        ./a.out
        ;;

    commit)
        git add $2
        git commit -m "$3"
        ;;  
    
    upstream)
        git push origin
        ;;
    
    downstream)
        git pull origin
        ;;

    *)
        echo $"Usage: $0 {compile <filename>|run|commit <filename> <commit message>|upstream}"

esac
